### ISSUE TITLE
Absolute positioning of <span> elements is prone to display errors

### ISSUE THREAD

**Issue by jkphl** [UmbraEngineering/Placeholder#4]
When using one of the `*span.js` variants, the created `<span>` elements are absolutely positioned (using their offset parent). If the page's layout is changed by some CSS modifications (e.g. a CSS class name is added / removed / changed), then **potentially a lot or all** placeholders on the page would have to be updated / redrawn. This doesn't happen automatically (yet?). When I try to redraw / reposition the placeholder `<spans>` manually (by calling `document.placeholderPolyfill()`, which should just do the trick as far as I understood) I get only errors. The reasons seems to be that int the function

``` JavaScript
function updatePlaceholder() {
    placeholder.innerHTML = getPlaceholderFor(elem);
    redrawPlaceholder();
}
```

the `placeholder` variable is undefined then.

In general, wouldn't it be better to not position the `<span>` elements absolutely, at least not in the way they are right now? Consider this:

``` html
<span style="position:relative" id="inserted-wrapper">
    <input type="text" name="xyz" value="abc"/>
    <span class="-placeholder" style="position:absolute; top: 0; z-index: 10000">Placeholder text ...</span>
</span>
```

I didn't test it (and left out some styles for the sake of readability), but I think it should work (at least with some little tweaks). Wrapping an outer `<span>` element with `position: relative` around the `<input>` (or `<textarea>`) shouldn't have any impact on the overall layout, but this way the placeholder `<span>` doesn't have to be repositioned each time the page layout changes, as it is "bound" to the `<input>` / `<texareas>`'s position.

I hope you understood what I'm talking about ...? What do you think?

**Comment by kbjr** [comment]
I do understand the issue you are seeing, for that reason I don't use this particular polyfill for anything complex (like interactive web apps), just for basic sites. I was trying to avoid using wrappers because it adds a new element into the DOM that the developer using the polyfill has to be aware of. For example, let's say we create an input and run the polyfill, resulting in a structure like what you show above:

``` html
<span style="position:relative" id="inserted-wrapper">
    <input type="text" name="xyz" value="abc"/>
    <span class="-placeholder" style="position:absolute; top: 0; z-index: 10000">Placeholder text ...</span>
</span>
```

Then, what if I change the location of that input?

``` javascript
document.querySelector('input[name=xyz]').style.paddingTop = '25px';
```

The issue of needing to update the positioning isn't solved as this would still cause the placeholder to be out of place. It also potentially breaks selectors:

``` html
<form>
    <input type="text" placeholder="foo" />
</form>
```

``` css
form > input {
    color: #08a;
}
```

The input above wouldn't be captured by the selector because it has been moved.

**Comment by jkphl** [comment]
Hi James,

I totally understand your concerns, and there would definitely arise new problems in those cases you are pointing out. However, I'm just trying to find a solution for my (not so special) requirement, which could in fact be easily solved (by using wrappers instead of the absolutely positioned `<span>`s). I'd also go for the absolutely positioned elements if the `document.placeholderPolyfill()` worked as expected – but unfortunately it doesn't.

It's probably the easiest solution for me to simply spawn a fork of your script and implement a version specific for my use case.

Thanks again for your response! :)

Cheers,
Joschi

**Comment by kbjr** [comment]
When you finish writing your new version, please send me a pull request. The whole point of this repo is to maintain different ways of fixing the same problem, and would be happy to add yours to the list :)

**Comment by jkphl** [comment]
:+1: Alright, I'll keep you posted! :)
